# Generated by Django 3.2.12 on 2022-05-20 07:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0002_auto_20220519_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrigister',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='userrigister',
            name='height',
            field=models.PositiveIntegerField(default=170),
        ),
        migrations.AddField(
            model_name='userrigister',
            name='pair_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='userrigister',
            name='pairids',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='userrigister',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userrigister',
            name='weight',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
