# Generated by Django 3.2.12 on 2022-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0003_auto_20220520_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrigister',
            name='fb',
            field=models.URLField(blank=True),
        ),
    ]
