# Generated by Django 3.2.12 on 2022-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0004_userrigister_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrigister',
            name='photo',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
