# Generated by Django 3.2.12 on 2022-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0005_alter_userrigister_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrigister',
            name='photo',
            field=models.ImageField(upload_to='image'),
        ),
    ]
