# Generated by Django 3.2.12 on 2022-05-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0006_alter_userrigister_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrigister',
            name='photo',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.CreateModel(
            name='Pairid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairid', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pairs.userrigister')),
            ],
        ),
    ]
