# Generated by Django 3.2.12 on 2022-05-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0007_auto_20220524_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrigister',
            name='intro',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='NotPairid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notpairid', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pairs.userrigister')),
            ],
        ),
    ]
