# Generated by Django 3.2.12 on 2022-06-10 07:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0008_auto_20220525_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrigister',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='userrigister',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='userrigister',
            name='pairids',
        ),
        migrations.AddField(
            model_name='userrigister',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
