# Generated by Django 3.2.12 on 2022-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0009_auto_20220610_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrigister',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
